management:
  endpoints:
    web:
      exposure:
          include: info, health, bus-refresh

server:
  port: ${PORT:8761}
  
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5000
    enable-self-preservation: false
