management:
  security:
    enabled: false

server:
  port: ${port:8777}

spring:
  cloud:
    config:
      enabled: true

      
#      eureka:
#        instance:
#          prefer-ip-address: true
#        client:
#          register-with-eureka: true
#          fetch-registry: true
#          service-url:
#            default-zone: http://localhost:8761/eureka
